# Config to extract SALSA feature for TAU-NIGENS Spatial Sound Events (TNSSE) 2021 dataset
data_dir: 'dataset/data'
feature_dir: 'dataset/features'
data:
  format: 'foa' # 'foa' | 'mic'
  fs: 24000
  n_fft: 1024
  win_len: 1024
  hop_len: 600  # 300 for 12.5ms for n_fft = 512; 150 for n_fft = 256
  fmin_doa: 20
  fmax_doa: 12000  # 'foa': 9000; 'mic': 4000
